name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: finefood
          MYSQL_DATABASE: finefood
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --use-pep517
    - name: Config the environment
      run: |
        echo "allowed_hosts=127.0.0.1,localhost" >> .env
        echo "django_session=django-insecure" >> .env
        echo "db_name=finefood" >> .env
        echo "db_user=root" >> .env
        echo "db_pass=finefood" >> .env
        echo "db_host=127.0.0.1" >> .env
        echo "db_port=3306" >> .env
    - name: Check the configuration
      run: |
        python manage.py check
    - name: Run Tests
      run: |
        python manage.py test
